version: '2'

services:

    nginx-proxy:
      image: jwilder/nginx-proxy:alpine
      restart: always
      ports:
        - "80:80"
        - "443:443"
      labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
      volumes:
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs:ro
        - conf.d:/etc/nginx/conf.d
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - vhost.d:/etc/nginx/vhost.d

    letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      volumes:
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs
        - conf.d:/etc/nginx/conf.d
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - vhost.d:/etc/nginx/vhost.d
      depends_on:
        - nginx-proxy

    rdiffbackup:
      build: ./rdiffbackup
      hostname: backup
      domainname: anonymous-proxy-servers.net
      environment:
        - VIRTUAL_PORT=8080
        - VIRTUAL_HOST=backup.anonymous-proxy-servers.net
        - LETSENCRYPT_HOST=backup.anonymous-proxy-servers.net
      volumes:
        - /root/Backup:/backups
        - /root/Restore:/restores
        - /root/rdiffweb_files/conf:/etc/rdiffweb

volumes:
  conf.d:
  certs:
  html:
  vhost.d:
