releases_dir:  /var/www/torupdates/htdocs/jondobrowser
download:
    archive_url: https://updates.anonymous-proxy-servers.net/jondobrowser/
    gpg_keyring: ../../gitian/gpg/jondobrowser.gpg
    bundles_url: https://updates.anonymous-proxy-servers.net/jondobrowser
    mars_url: https://updates.anonymous-proxy-servers.net/jondobrowser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    #alpha: 6.5n
    release: 6.5n
    #nightly: 6.5n
versions:
    6.5n:
        platformVersion: 45.2.0
        detailsURL: https://blog.torproject.org/blog/tor-browser-601-released
        incremental_from:
          - 5.5.5
          - 6.0
        migrate_archs:
          osx32: osx64
        osx32:
            minSupportedOSVersion: 10.8
            detailsURL: https://blog.torproject.org/blog/end-life-plan-tor-browser-32-bit-macs#updating
