version: '3.1'

services:

    nginx-proxy:
      image: jwilder/nginx-proxy:alpine
      ports:
        - "78.129.167.102:80:80"
        - "78.129.167.102:443:443"
      depends_on:
        - jenkins
        - subversion
        - icinga2
        - mail2
      labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
      volumes:
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /tmp/nginx-proxy/conf.d:/etc/nginx/conf.d
        - ./vhost.d:/etc/nginx/vhost.d

    letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      volumes:
        - certs:/etc/nginx/certs
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /tmp/nginx-proxy/conf.d:/etc/nginx/conf.d
        - ./vhost.d:/etc/nginx/vhost.d
      depends_on:
        - nginx-proxy

    jenkins:
      image: jenkins/jenkins:lts
      hostname: build
      domainname: anonymous-proxy-servers.net
      environment:
        - VIRTUAL_HOST=build.anonymous-proxy-servers.net
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=build.anonymous-proxy-servers.net
        - LETSENCRYPT_EMAIL=oliver.meyer@jondos.de
      volumes:
        - /root/jenkins-files:/var/jenkins_home
      ports:
        - "50000:50000"

    subversion:
      image: marvambass/subversion
      hostname: svn
      domainname: jondos.de
      environment:
        - VIRTUAL_HOST=svn.jondos.de
        - LETSENCRYPT_HOST=svn.jondos.de
        - LETSENCRYPT_EMAIL=oliver.meyer@jondos.de
      volumes:
        - /root/svn-files/svn:/var/local/svn
        - /root/svn-files/dav_svn:/etc/apache/dav_svn

    icinga2:
      image: jordan/icinga2
      hostname: monitor
      domainname: jondos.de
      environment:
        - VIRTUAL_HOST=monitor.jondos.de
        - LETSENCRYPT_HOST=monitor.jondos.de
        - LETSENCRYPT_EMAIL=oliver.meyer@jondos.de
      volumes:
        - /root/icinga2files/etc/icinga2:/etc/icinga2
        - /root/icinga2files/etc/icingaweb2:/etc/icingaweb2
        - /root/icinga2files/var/lib/icinga2:/var/lib/icinga2
        - /root/icinga2files/var/lib/mysql:/var/lib/mysql
      
    mail2:
      image: tvial/docker-mailserver:latest
      hostname: mail
      domainname: jondos.de
      ports:
        - "78.129.167.102:25:25"
        - "110:110"
        - "143:143"
        - "465:465"
        - "10465:465"
        - "587:587"
        - "10587:587"
        - "993:993"
        - "995:995"
      volumes:
        - /root/mail-files/data:/var/mail
        - /root/mail-files/state:/var/mail-state
        - /root/mail-files/config:/tmp/docker-mailserver
        - certs:/etc/letsencrypt/live
      environment:
        - VIRTUAL_HOST=mail.jondos.de
        - LETSENCRYPT_HOST=mail.jondos.de
        - LETSENCRYPT_EMAIL=oliver.meyer@jondos.de
        - ENABLE_SPAMASSASSIN=1
        - ENABLE_CLAMAV=1
        - ENABLE_FAIL2BAN=0
        - ENABLE_POSTGREY=1
        - ONE_DIR=1
        - DMS_DEBUG=1
        - ENABLE_SASLAUTHD=0
        - SSL_TYPE=letsencrypt
        - ENABLE_POP3=1
      cap_add:
        - NET_ADMIN
        - SYS_PTRACE

    shop2:
      build: ./shop
      hostname: shop
      domainname: anonymous-proxy-servers.net
      environment:
        - VIRTUAL_HOST=shop.anonymous-proxy-servers.net
      volumes:
        - /root/shop/db:/var/lib/mysql
      #ports:
      #  - "78.129.167.5:80:80"
      #  - "78.129.167.5:443:443"

    ipcheck2:
      build: ./ipcheck
      hostname: ip-check.info
      volumes:
        - ipcheck-log:/var/log/apache2
      ports:
        - "21:21"
      environment:
        - VIRTUAL_HOST=ip-check.info,ipcheck.info,ip-check.org

volumes:
  certs:
  html:

networks:
  noproxy:
