#!/usr/bin/env ansible-playbook  -i ../inventory -K
---
- hosts: Backup
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: fetch key from backup server
    shell: "docker exec backup_rdiffbackup_1 getkey > /tmp/backupkey"

  - name: fetch key from backup server, part 2
    fetch: 
      src: /tmp/backupkey
      dest: /tmp/backupkey
      flat: yes
 
  - name: remove temp file
    file: 
      path: /tmp/backupkey
      state: absent

- hosts: jondos-backupclients
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: create backup user
    user:
      name: backup
      groups: sudo
      append: true

  - name: install required packages
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - rdiff-backup

  - name: enable access from backup server
    authorized_key:
      state: present
      user: backup
      key: "{{ lookup('file', '/tmp/backupkey') }}"
